#ffa - by qNoKeRp

#Задержка до телепортации на прежнее место победителя
DelayFinishTP: 60

#Время отведенное на пвп (по окончанию - ничья, всех тепает назад)
FightTime: 1800

#Задержка до телепортации на арену
DelayStartTP: 7